source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'URBNSwiftAlert_Example' do
  pod 'URBNSwiftAlert', :path => '../'
  pod 'URBNConvenience'
  target 'URBNSwiftAlert_Tests' do
    inherit! :search_paths

    
  end
end
